# Generated by Django 3.2.7 on 2021-10-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protubes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protube',
            name='video',
        ),
        migrations.AddField(
            model_name='protube',
            name='description',
            field=models.CharField(default=5, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protube',
            name='image',
            field=models.ImageField(blank=True, upload_to='namefile'),
        ),
    ]
